plugins {
    id 'multiloader-loader'
    id 'net.neoforged.moddev'
    id "com.matthewprenger.cursegradle" version "1.4.0"
}

neoForge {
    version = neoforge_version
    def at = project(':common').file('src/main/resources/META-INF/accesstransformer.cfg')
    if (at.exists()) {
        accessTransformers.from(at.absolutePath)
    }
    parchment {
        minecraftVersion = parchment_minecraft
        mappingsVersion = parchment_version
    }
    runs {
        configureEach {
            systemProperty('neoforge.enabledGameTestNamespaces', mod_id)
            ideName = "NeoForge ${it.name.capitalize()} (${project.path})" // Unify the run config names with fabric
        }
        client {
            client()
        }
        server {
            server()
        }
    }
    mods {
        "${mod_id}" {
            sourceSet sourceSets.main
        }
    }
}

sourceSets.main.resources { srcDir 'src/generated/resources' }

dependencies {
    // Item Obliterator
    implementation "maven.modrinth:item-obliterator:${forge_item_obliterator_version}"
    implementation "maven.modrinth:necronomicon:${forge_necronomicon_version}"

    // Reliable Remover
    implementation "curse.maven:reliable-remover-1420447:7415736"

    // EMI
    implementation "dev.emi:emi-neoforge:${emi_version}"

    // Cloth Config
    implementation "me.shedaniel.cloth:cloth-config-neoforge:${cloth_config_version}"
}


curseforge {
    apiKey = System.getenv("CURSEFORGE_TOKEN") ?: "0"
    project {
        id = "1414959"
        releaseType = "release"
        changelog = file('../CHANGELOG.md')
        changelogType = 'markdown'

        addGameVersion "1.21.1"
        addGameVersion "Java 21"
        addGameVersion "NeoForge"

        mainArtifact(jar.archiveFile) {
            displayName = "Reliable Recipes NeoForge ${project.minecraft_version} - ${project.version}"
        }

        relations {
            optionalDependency "reliable-remover"
            optionalDependency "item-obliterator"
            optionalDependency "cloth-config"
        }
    }
}